# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e0ffa441d5baa32a7c8851c2e26720263e77d84bd298688a788955c756cdc93226c89910975e275d2e75bd1187373b8a443d9607a7a96130ab707266c4cac412

test:
  secret_key_base: e056f896c009ddbffaf036dbe6de1b59710e4cba45d6dcf8a9ab8d707edc28456cec5739f9b5c710e2f40f45d4098073b7add810aa973bd43306604604ffb47e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
